import { createContext, useContext, useState, useEffect, useCallback, type ReactNode } from 'react';

type Language = 'pt' | 'en' | 'es' | 'fr';

type Translations = Record<Language, Record<string, string>>;

const translations: Translations = {
  pt: {
    'venue.name': 'MAM Salvador',
    'venue.status': 'Aberto agora',
    'exhibition.label': 'EXPOSIÇÃO PRINCIPAL',
    'exhibition.title': 'Uma História da Arte Brasileira',
    'exhibition.subtitle': '80 obras do MAM Rio · Entrada gratuita',
    'exhibition.description': '80 obras do acervo do MAM Rio chegam a Salvador numa celebração da arte brasileira do século XX. De Portinari a Anita Malfatti, de Di Cavalcanti a Lygia Clark — um percurso que atravessa movimentos, gerações e visões de Brasil.',
    'checkin.cta': 'Dê seu pulso e acesse o guia da exposição',
    'checkin.cta.returning': 'Bem-vindo de volta, {name}! 👋 Dê seu pulso e acesse o guia.',
    'cpf.label': 'Seu CPF',
    'cpf.placeholder': '000.000.000-00',
    'source.question': 'Como soube desta exposição?',
    'source.social': 'Redes sociais',
    'source.referral': 'Indicação',
    'source.walked_by': 'Passei na frente',
    'source.tv': 'Jornal / TV',
    'source.school': 'Escola / faculdade',
    'source.other': 'Outro',
    'source.other_placeholder': 'Qual?',
    'button.pulse': 'Pulsar',
    'button.pulsing': 'Pulsando...',
    'button.accessing': 'Acessando...',
    'error.invalid_cpf': 'CPF inválido.',
    'error.invalid_email': 'E-mail inválido.',
    'identity.question': 'Como prefere se identificar?',
    'identity.cpf': 'CPF',
    'identity.email': 'E-mail',
    'identity.cpf_hint': 'Para quem mora no Brasil ou tem CPF',
    'identity.email_hint': 'Recomendado para visitantes internacionais',
    'identity.cpf_placeholder': '000.000.000-00',
    'identity.email_placeholder': 'seu@email.com',
    'footer.lgpd.checkbox': 'Concordo com os termos de uso e privacidade',
    'footer.lgpd.link': 'Seus dados estão protegidos pela LGPD',
    'login.admin': 'Gestão',
    'success.granted': 'Acesso liberado!',
    'success.redirecting': 'Redirecionando para o guia...',
    'guide.hours': 'Ter a Dom · 10h às 18h',
    'guide.highlights': 'Destaques',
    'guide.works_count': 'OBRAS',
    'guide.audio_label': 'Áudio-guia: {title}',
    'guide.other_exhibitions': 'Também em cartaz',
    'guide.room_prefix': 'Sala',
    'feedback.title': 'Curtiu a visita?',
    'feedback.subtitle': 'Compartilhe que você fez a cultura pulsar hoje.',
    'feedback.placeholder': 'O que mais te marcou nessa experiência?',
    'feedback.button.send': 'Enviar avaliação',
    'feedback.button.share': 'Compartilhar meu pulso',
    'feedback.label.1': 'Pode melhorar',
    'feedback.label.2': 'Pode melhorar',
    'feedback.label.3': 'Interessante',
    'feedback.label.4': 'Muito bom',
    'feedback.label.5': 'Incrível 🔥',
    'feedback.success': '✨ Obrigado por fazer a cultura pulsar!',
    'feedback.title.page': 'Avaliação',
    'feedback.desc.page': 'Sua opinião é fundamental para melhorar a experiência cultural.',
    'feedback.question': 'Como foi sua experiência?',
    'feedback.comment.label': 'Deixe um comentário (opcional)',
    'feedback.comment.placeholder': 'O que você mais gostou na exposição?',
    'feedback.button.submit': 'Concluir e Enviar',
    'feedback.thanks': 'Obrigado!',
    'feedback.thanks.desc': 'Sua avaliação ajuda o MAM Salvador a criar experiências cada vez melhores.',
    'feedback.back_home': '← Voltar ao início',
    'share.label': 'Eu fiz a cultura pulsar hoje.',
    'share.button.generate': 'Gerando...',
    'share.button.share': 'Compartilhar',
    'share.button.saving': 'Salvando...',
    'share.button.save': 'Salvar',
    'share.back': '← Voltar ao guia',
    'share.message': 'Eu fiz a cultura pulsar hoje. 🔴\n\nUma História da Arte Brasileira · MAM Salvador',
    'checkin.form.title': 'Crie seu Perfil Cultural',
    'checkin.form.desc': 'Responda rápido para desbloquear uma experiência única e acessível.',
    'checkin.form.trust': 'Protegido pela LGPD. Usado apenas para garantir um acesso único e seguro.',
    'checkin.form.acc.help': 'Ajude-nos a adaptar a experiência para você.',
    'checkin.form.cpf.label': 'CPF',
    'checkin.form.cpf.placeholder': '000.000.000-00',
    'checkin.form.nome.label': 'Nome',
    'checkin.form.nome.placeholder': 'Como quer ser chamado?',
    'checkin.form.nascimento.label': 'Ano de nascimento',
    'checkin.form.nascimento.placeholder': 'Ex: 1992',
    'checkin.form.genero.label': 'Identidade de gênero',
    'checkin.form.genero.f': 'Feminino',
    'checkin.form.genero.m': 'Masculino',
    'checkin.form.genero.nb': 'Não-binário',
    'checkin.form.genero.pnd': 'Prefiro não dizer',
    'checkin.form.acc.label': 'Necessidades de acessibilidade',
    'checkin.form.acc.optional': '(opcional)',
    'checkin.form.acc.mob': 'Mobilidade reduzida',
    'checkin.form.acc.vis': 'Baixa visão',
    'checkin.form.acc.sen': 'Sensibilidade sensorial',
    'checkin.form.acc.neu': 'Neurodivergência',
    'checkin.form.acc.outra': 'Outra',
    'checkin.form.acc.outra_placeholder': 'Qual?',
    'checkin.form.origem.label': 'De onde você vem?',
    'checkin.form.origem.sal': 'Salvador',
    'checkin.form.origem.int': 'Interior da Bahia',
    'checkin.form.origem.out': 'Outro estado',
    'checkin.form.origem.tur': 'Turista internacional',
    'checkin.form.origem.out_placeholder': 'Qual cidade / estado?',
    'checkin.form.origem.tur_placeholder': 'Qual país e cidade?',
    'checkin.form.lgpd': 'Concordo com o uso dos meus dados para melhoria da experiência cultural e relatórios de impacto do espaço, conforme a LGPD.',
    'checkin.form.submit': 'Registrar e acessar guia',
    'checkin.form.validating': 'Validando...',
    'checkin.form.header': 'Primeiro pulso!',
    'checkin.form.header_desc': 'Conte um pouco sobre você. Esse cadastro é único — nas próximas visitas, basta o {identity}.',
    'checkin.form.creating': 'Criando perfil...',
    'checkin.form.create_profile': 'Criar meu perfil →',
    'checkin.form.email_label': 'E-mail',
    'checkin.form.already_registered': 'CPF já registrado. Use a tela de entrada.',
    'checkin.form.go_to_login': '→ Ir para a tela de entrada',
    'checkin.form.unexpected_error': 'Erro inesperado. Tente novamente.',
    'checkin.form.origem.detail_city': 'Qual cidade / estado?',
    'checkin.form.origem.detail_country': 'Qual país?'
  },
  en: {
    'venue.name': 'MAM Salvador',
    'venue.status': 'Open now',
    'exhibition.label': 'PRINCIPAL EXHIBITION',
    'exhibition.title': 'A History of Brazilian Art',
    'exhibition.subtitle': '80 works from MAM Rio · Free admission',
    'exhibition.description': '80 works from the MAM Rio collection arrive in Salvador in a celebration of 20th-century Brazilian art. From Portinari to Anita Malfatti, from Di Cavalcanti to Lygia Clark — a journey through movements, generations, and visions of Brazil.',
    'checkin.cta': 'Your guide starts with your pulse.',
    'checkin.cta.returning': 'Welcome back, {name}! 👋 Your guide starts with your pulse.',
    'cpf.label': 'Your Tax ID — your identity in our space',
    'cpf.placeholder': '000.000.000-00',
    'source.question': 'How did you hear about this exhibition?',
    'source.social': 'Social media',
    'source.referral': 'Referral',
    'source.walked_by': 'Walked by',
    'source.tv': 'Newspaper / TV',
    'source.school': 'School / College',
    'source.other': 'Other',
    'source.other_placeholder': 'Which one?',
    'button.pulse': 'Pulse',
    'button.pulsing': 'Finding your pulse...',
    'button.accessing': 'Accessing...',
    'error.invalid_cpf': 'The provided Tax ID does not seem valid.',
    'error.invalid_email': 'Invalid email address.',
    'identity.question': 'How would you like to identify yourself?',
    'identity.cpf': 'CPF',
    'identity.email': 'Email',
    'identity.cpf_hint': 'For users who live in Brazil or have a CPF',
    'identity.email_hint': 'Recommended for international visitors',
    'identity.cpf_placeholder': '000.000.000-00',
    'identity.email_placeholder': 'your@email.com',
    'footer.lgpd.checkbox': 'I agree to the use of my data to improve the cultural experience',
    'footer.lgpd.link': 'Protected by LGPD',
    'login.admin': 'Management',
    'success.granted': 'Access granted!',
    'success.redirecting': 'Redirecting to the guide...',
    'guide.hours': 'Tue to Sun · 10am to 6pm',
    'guide.highlights': 'Highlights',
    'guide.works_count': 'WORKS',
    'guide.audio_label': 'Audio guide: {title}',
    'guide.other_exhibitions': 'Also showing',
    'guide.room_prefix': 'Room',
    'feedback.title': 'Did you enjoy the visit?',
    'feedback.subtitle': 'Share that you made culture pulse today.',
    'feedback.placeholder': 'What stood out most for you?',
    'feedback.button.send': 'Send review',
    'feedback.button.share': 'Share my pulse',
    'feedback.label.1': 'Could be better',
    'feedback.label.2': 'Could be better',
    'feedback.label.3': 'Interesting',
    'feedback.label.4': 'Very good',
    'feedback.label.5': 'Amazing 🔥',
    'feedback.success': '✨ Thanks for making culture pulse!',
    'feedback.title.page': 'Review',
    'feedback.desc.page': 'Your opinion is critical for improving the cultural experience.',
    'feedback.question': 'How was your experience?',
    'feedback.comment.label': 'Leave a comment (optional)',
    'feedback.comment.placeholder': 'What did you like most about the exhibition?',
    'feedback.button.submit': 'Complete and Send',
    'feedback.thanks': 'Thank you!',
    'feedback.thanks.desc': 'Your review helps MAM Salvador create better experiences.',
    'feedback.back_home': '← Back to home',
    'share.label': 'I made culture pulse today.',
    'share.button.generate': 'Generating...',
    'share.button.share': 'Share',
    'share.button.saving': 'Saving...',
    'share.button.save': 'Save',
    'share.back': '← Back to guide',
    'share.message': 'I made culture pulse today. 🔴\n\nA History of Brazilian Art · MAM Salvador',
    'checkin.form.title': 'Create your Cultural Profile',
    'checkin.form.desc': 'Answer quickly to unlock a unique and accessible experience.',
    'checkin.form.trust': 'Protected by LGPD. Used only to ensure a unique and secure access.',
    'checkin.form.acc.help': 'Help us adapt the experience for you.',
    'checkin.form.cpf.label': 'ID Number',
    'checkin.form.cpf.placeholder': '000.000.000-00',
    'checkin.form.nome.label': 'Name',
    'checkin.form.nome.placeholder': 'How would you like to be called?',
    'checkin.form.nascimento.label': 'Birth Year',
    'checkin.form.nascimento.placeholder': 'E.g: 1992',
    'checkin.form.genero.label': 'Gender Identity',
    'checkin.form.genero.f': 'Female',
    'checkin.form.genero.m': 'Male',
    'checkin.form.genero.nb': 'Non-binary',
    'checkin.form.genero.pnd': 'Prefer not to say',
    'checkin.form.acc.label': 'Accessibility needs',
    'checkin.form.acc.optional': '(optional)',
    'checkin.form.acc.mob': 'Reduced mobility',
    'checkin.form.acc.vis': 'Low vision',
    'checkin.form.acc.sen': 'Sensory sensitivity',
    'checkin.form.acc.neu': 'Neurodivergence',
    'checkin.form.acc.outra': 'Other',
    'checkin.form.acc.outra_placeholder': 'Which one?',
    'checkin.form.origem.label': 'Where are you from?',
    'checkin.form.origem.sal': 'Salvador',
    'checkin.form.origem.int': 'Bahia state',
    'checkin.form.origem.out': 'Other state',
    'checkin.form.origem.tur': 'International Tourist',
    'checkin.form.origem.out_placeholder': 'Which city / state?',
    'checkin.form.origem.tur_placeholder': 'Which country and city?',
    'checkin.form.lgpd': 'I agree with the use of my data to improve the cultural experience and space impact reports, in accordance with the law.',
    'checkin.form.submit': 'Register and access guide',
    'checkin.form.validating': 'Validating...',
    'checkin.form.header': 'First pulse!',
    'checkin.form.header_desc': 'Tell us a bit about yourself. This registration is one-time only — next visits, just your {identity}.',
    'checkin.form.creating': 'Creating profile...',
    'checkin.form.create_profile': 'Create my profile →',
    'checkin.form.email_label': 'Email',
    'checkin.form.already_registered': 'CPF already registered. Use the login screen.',
    'checkin.form.go_to_login': '→ Go to login screen',
    'checkin.form.unexpected_error': 'Unexpected error. Please try again.',
    'checkin.form.origem.detail_city': 'Which city / state?',
    'checkin.form.origem.detail_country': 'Which country?'
  },
  es: {
    'venue.name': 'MAM Salvador',
    'venue.status': 'Abierto ahora',
    'exhibition.label': 'EXPOSICIÓN PRINCIPAL',
    'exhibition.title': 'Una Historia del Arte Brasileño',
    'exhibition.subtitle': '80 obras del MAM Rio · Entrada gratuita',
    'exhibition.description': '80 obras de la colección del MAM Rio llegan a Salvador en una celebración del arte brasileño del siglo XX. De Portinari a Anita Malfatti, de Di Cavalcanti a Lygia Clark — un recorrido por movimientos, generaciones y visiones de Brasil.',
    'checkin.cta': 'Su guía comienza por su pulso.',
    'checkin.cta.returning': '¡Bienvenido de nuevo, {name}! 👋 Su guía comienza por su pulso.',
    'cpf.label': 'Tu RUT/DNI — tu identidad en el espacio',
    'cpf.placeholder': 'Documento de Identidad',
    'source.question': '¿Cómo te enteraste de esta exposición?',
    'source.social': 'Redes sociales',
    'source.referral': 'Indicación',
    'source.walked_by': 'Pasando por la calle',
    'source.tv': 'Periódico / TV',
    'source.school': 'Escuela / Universidad',
    'source.other': 'Otro',
    'source.other_placeholder': '¿Cuál?',
    'button.pulse': 'Pulsar',
    'button.pulsing': 'Buscando su pulso...',
    'button.accessing': 'Accediendo...',
    'error.invalid_cpf': 'El documento ingresado no parece válido.',
    'error.invalid_email': 'Dirección de correo inválida.',
    'identity.question': '¿Cómo prefiere identificarse?',
    'identity.cpf': 'CPF',
    'identity.email': 'Correo electrónico',
    'identity.cpf_hint': 'Para usuarios que viven en Brasil o tienen CPF',
    'identity.email_hint': 'Recomendado para visitantes internacionales',
    'identity.cpf_placeholder': '000.000.000-00',
    'identity.email_placeholder': 'su@correo.com',
    'footer.lgpd.checkbox': 'Acepto el uso de mis datos para mejorar la experiencia cultural',
    'footer.lgpd.link': 'Protegido por la LGPD',
    'login.admin': 'Gestión',
    'success.granted': '¡Acceso liberado!',
    'success.redirecting': 'Redirigiendo a la guía...',
    'guide.hours': 'Mar a Dom · 10h a 18h',
    'guide.highlights': 'Destacados',
    'guide.works_count': 'OBRAS',
    'guide.audio_label': 'Audioguía: {title}',
    'guide.other_exhibitions': 'También en cartelera',
    'guide.room_prefix': 'Sala',
    'feedback.title': '¿Te gustó la visita?',
    'feedback.subtitle': 'Comparte que hiciste pulsar la cultura hoy.',
    'feedback.placeholder': '¿Qué fue lo que más te marcó de esta experiencia?',
    'feedback.button.send': 'Enviar evaluación',
    'feedback.button.share': 'Compartir mi pulso',
    'feedback.label.1': 'Puede mejorar',
    'feedback.label.2': 'Puede mejorar',
    'feedback.label.3': 'Interesante',
    'feedback.label.4': 'Muy bueno',
    'feedback.label.5': 'Increíble 🔥',
    'feedback.success': '✨ ¡Gracias por hacer pulsar la cultura!',
    'feedback.title.page': 'Evaluación',
    'feedback.desc.page': 'Su opinión é fundamental para mejorar la experiencia cultural.',
    'feedback.question': '¿Cómo fue su experiencia?',
    'feedback.comment.label': 'Deje um comentário (opcional)',
    'feedback.comment.placeholder': '¿Qué fue lo que más le gustó de la exposición?',
    'feedback.button.submit': 'Concluir y Enviar',
    'feedback.thanks': '¡Gracias!',
    'feedback.thanks.desc': 'Su evaluación ayuda al MAM Salvador a crear experiencias mejores.',
    'feedback.back_home': '← Voltar à página inicial',
    'share.label': 'Hice pulsar la cultura hoy.',
    'share.button.generate': 'Generando...',
    'share.button.share': 'Compartir',
    'share.button.saving': 'Guardando...',
    'share.button.save': 'Guardar',
    'share.back': '← Voltar à guia',
    'share.message': 'Hice pulsar la cultura hoy. 🔴\n\nUna Historia del Arte Brasileño · MAM Salvador',
    'checkin.form.title': 'Crea tu Perfil Cultural',
    'checkin.form.desc': 'Responde rápido para desbloquear una experiencia única y accesible.',
    'checkin.form.trust': 'Protegido por la LGPD. Utilizado solo para garantizar un acceso único y seguro.',
    'checkin.form.acc.help': 'Ayúdanos a adaptar la experiencia para ti.',
    'checkin.form.cpf.label': 'Documento',
    'checkin.form.cpf.placeholder': '000.000.000-00',
    'checkin.form.nome.label': 'Nombre',
    'checkin.form.nome.placeholder': '¿Cómo quieres que te llamemos?',
    'checkin.form.nascimento.label': 'Año de nacimiento',
    'checkin.form.nascimento.placeholder': 'Ej: 1992',
    'checkin.form.genero.label': 'Identidad de género',
    'checkin.form.genero.f': 'Femenino',
    'checkin.form.genero.m': 'Masculino',
    'checkin.form.genero.nb': 'No binario',
    'checkin.form.genero.pnd': 'Prefiero no decirlo',
    'checkin.form.acc.label': 'Necesidades de accesibilidad',
    'checkin.form.acc.optional': '(opcional)',
    'checkin.form.acc.mob': 'Movilidad reducida',
    'checkin.form.acc.vis': 'Baja visión',
    'checkin.form.acc.sen': 'Sensibilidad sensorial',
    'checkin.form.acc.neu': 'Neurodivergencia',
    'checkin.form.acc.outra': 'Otra',
    'checkin.form.acc.outra_placeholder': '¿Cuál?',
    'checkin.form.origem.label': '¿De dónde vienes?',
    'checkin.form.origem.sal': 'Salvador',
    'checkin.form.origem.int': 'Interior de Bahía',
    'checkin.form.origem.out': 'Otro estado',
    'checkin.form.origem.tur': 'Turista internacional',
    'checkin.form.origem.out_placeholder': '¿Qué ciudad / estado?',
    'checkin.form.origem.tur_placeholder': '¿Qué país y ciudad?',
    'checkin.form.lgpd': 'Estoy de acuerdo con el uso de mis datos para mejorar la experiencia cultural y los informes de impacto del espacio.',
    'checkin.form.submit': 'Registrar y acceder a la guía',
    'checkin.form.validating': 'Validando...',
    'checkin.form.header': '¡Primer pulso!',
    'checkin.form.header_desc': 'Cuéntanos un poco sobre ti. Este registro es único — en las próximas visitas, solo tu {identity}.',
    'checkin.form.creating': 'Creando perfil...',
    'checkin.form.create_profile': 'Crear mi perfil →',
    'checkin.form.email_label': 'Correo electrónico',
    'checkin.form.already_registered': 'CPF ya registrado. Usa la pantalla de entrada.',
    'checkin.form.go_to_login': '→ Ir a la pantalla de entrada',
    'checkin.form.unexpected_error': 'Error inesperado. Intenta de nuevo.',
    'checkin.form.origem.detail_city': '¿Qué ciudad / estado?',
    'checkin.form.origem.detail_country': '¿Qué país?'
  },
  fr: {
    'venue.name': 'MAM Salvador',
    'venue.status': 'Ouvert maintenant',
    'exhibition.label': 'EXPOSITION PRINCIPALE',
    'exhibition.title': 'Une Histoire de L\'Art Brésilien',
    'exhibition.subtitle': '80 œuvres du MAM Rio · Entrée gratuite',
    'exhibition.description': '80 œuvres de la collection du MAM Rio arrivent à Salvador pour une célébration de l\'art brésilien du XXe siècle. De Portinari à Anita Malfatti, de Di Cavalcanti à Lygia Clark — un voyage à travers les mouvements, les générations et les visions du Brésil.',
    'checkin.cta': 'Votre guide commence par votre pouls.',
    'checkin.cta.returning': 'Content de vous revoir, {name}! 👋 Votre guide commence par votre pouls.',
    'cpf.label': 'Votre pièce d\'identité — votre pass d\'accès',
    'cpf.placeholder': 'Numéro d\'identité',
    'source.question': 'Comment avez-vous entendu parler de cette exposition?',
    'source.social': 'Réseaux sociaux',
    'source.referral': 'Recommandation',
    'source.walked_by': 'En passant par là',
    'source.tv': 'Journal / TV',
    'source.school': 'École / Université',
    'source.other': 'Autre',
    'source.other_placeholder': 'Lequel?',
    'button.pulse': 'Pulser',
    'button.pulsing': 'Recherche de votre pouls...',
    'button.accessing': 'Accès en cours...',
    'error.invalid_cpf': 'Le document fourni ne semble pas valide.',
    'error.invalid_email': 'Adresse e-mail invalide.',
    'identity.question': 'Comment souhaitez-vous vous identifier ?',
    'identity.cpf': 'CPF',
    'identity.email': 'E-mail',
    'identity.cpf_hint': 'Pour les utilisateurs vivant au Brésil ou ayant un CPF',
    'identity.email_hint': 'Recommandé pour les visiteurs internationaux',
    'identity.cpf_placeholder': '000.000.000-00',
    'identity.email_placeholder': 'votre@email.com',
    'footer.lgpd.checkbox': 'J\'accepte l\'utilisation de mes données pour améliorer l\'expérience culturelle',
    'footer.lgpd.link': 'Protégé par la LGPD',
    'login.admin': 'Gestion',
    'success.granted': 'Accès accordé!',
    'success.redirecting': 'Redirection vers le guide...',
    'guide.hours': 'Mar à Dim · 10h à 18h',
    'guide.highlights': 'Œuvres phares',
    'guide.works_count': 'ŒUVRES',
    'guide.audio_label': 'Audio-guide : {title}',
    'guide.other_exhibitions': 'À l\'affiche aussi',
    'guide.room_prefix': 'Salle',
    'feedback.title': 'Avez-vous aimé la visite ?',
    'feedback.subtitle': 'Partagez que vous avez fait vibrer la culture aujourd\'hui.',
    'feedback.placeholder': 'Qu\'est-ce qui vous a le plus marqué dans cette expérience ?',
    'feedback.button.send': 'Envoyer l\'avis',
    'feedback.button.share': 'Partager mon pouls',
    'feedback.label.1': 'Peut mieux faire',
    'feedback.label.2': 'Peut mieux faire',
    'feedback.label.3': 'Intéressant',
    'feedback.label.4': 'Très bien',
    'feedback.label.5': 'Incroyable 🔥',
    'feedback.success': '✨ Merci de faire vibrer la culture !',
    'feedback.title.page': 'Évaluation',
    'feedback.desc.page': 'Votre avis est essentiel pour améliorer l\'expérience culturelle.',
    'feedback.question': 'Comment s\'est passée votre visite ?',
    'feedback.comment.label': 'Laisser un commentaire (optionnel)',
    'feedback.comment.placeholder': 'Qu\'avez-vous le plus aimé dans l\'exposition ?',
    'feedback.button.submit': 'Terminer et envoyer',
    'feedback.thanks': 'Merci !',
    'feedback.thanks.desc': 'Votre avis aide le MAM Salvador à créer de meilleures expériences.',
    'feedback.back_home': '← Retour à l\'accueil',
    'share.label': 'J\'ai fait vibrer la culture aujourd\'hui.',
    'share.button.generate': 'Génération...',
    'share.button.share': 'Partager',
    'share.button.saving': 'Enregistrement...',
    'share.button.save': 'Enregistrer',
    'share.back': '← Retour au guide',
    'share.message': 'J\'ai fait vibrer la culture aujourd\'hui. 🔴\n\nUne Histoire de L\'Art Brésilien · MAM Salvador',
    'checkin.form.title': 'Créez votre Profil Culturel',
    'checkin.form.desc': 'Répondez rapidement pour débloquer une expérience unique et accessible.',
    'checkin.form.trust': 'Protégé par la LGPD. Utilisé uniquement pour garantir un accès unique et sécurisé.',
    'checkin.form.acc.help': 'Aidez-nous à adapter l\'expérience pour vous.',
    'checkin.form.cpf.label': 'Document d\'identité',
    'checkin.form.cpf.placeholder': '000.000.000-00',
    'checkin.form.nome.label': 'Nom',
    'checkin.form.nome.placeholder': 'Comment souhaitez-vous être appelé(e) ?',
    'checkin.form.nascimento.label': 'Année de naissance',
    'checkin.form.nascimento.placeholder': 'Ex : 1992',
    'checkin.form.genero.label': 'Identité de genre',
    'checkin.form.genero.f': 'Féminin',
    'checkin.form.genero.m': 'Masculin',
    'checkin.form.genero.nb': 'Non-binaire',
    'checkin.form.genero.pnd': 'Je préfère ne pas dire',
    'checkin.form.acc.label': 'Besoins d\'accessibilité',
    'checkin.form.acc.optional': '(optionnel)',
    'checkin.form.acc.mob': 'Mobilité réduite',
    'checkin.form.acc.vis': 'Basse vision',
    'checkin.form.acc.sen': 'Sensibilité sensorielle',
    'checkin.form.acc.neu': 'Neurodivergence',
    'checkin.form.acc.outra': 'Autre',
    'checkin.form.acc.outra_placeholder': 'Lequel ?',
    'checkin.form.origem.label': 'D\'où venez-vous ?',
    'checkin.form.origem.sal': 'Salvador',
    'checkin.form.origem.int': 'Intérieur de Bahia',
    'checkin.form.origem.out': 'Autre état',
    'checkin.form.origem.tur': 'Touriste international',
    'checkin.form.origem.out_placeholder': 'Quelle ville / quel état ?',
    'checkin.form.origem.tur_placeholder': 'Quel pays et quelle ville ?',
    'checkin.form.lgpd': 'J\'accepte l\'utilisation de mes données pour améliorer l\'expérience culturelle et les rapports d\'impact de l\'espace, conformément à la LGPD.',
    'checkin.form.submit': 'S\'inscrire et accéder au guide',
    'checkin.form.validating': 'Validation...',
    'checkin.form.header': 'Premier pouls !',
    'checkin.form.header_desc': 'Parlez-nous un peu de vous. Cette inscription est unique — lors de vos prochaines visites, votre {identity} suffira.',
    'checkin.form.creating': 'Création du profil...',
    'checkin.form.create_profile': 'Créer mon profil →',
    'checkin.form.email_label': 'E-mail',
    'checkin.form.already_registered': 'CPF déjà enregistré. Utilisez l\'écran d\'entrée.',
    'checkin.form.go_to_login': '→ Aller à l\'écran d\'entrée',
    'checkin.form.unexpected_error': 'Erreur inattendue. Veuillez réessayer.',
    'checkin.form.origem.detail_city': 'Quelle ville / quel état ?',
    'checkin.form.origem.detail_country': 'Quel pays ?',
  }
};

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, variables?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('pt');

  useEffect(() => {
    const savedLang = localStorage.getItem('pulso:lang') as Language;
    if (savedLang && ['pt', 'en', 'es', 'fr'].includes(savedLang)) {
      setLanguageState(savedLang);
    } else {
      // Auto-detect browser language
      const browserLang = navigator.language.split('-')[0] as Language;
      if (['pt', 'en', 'es', 'fr'].includes(browserLang)) {
        setLanguageState(browserLang);
      } else {
        setLanguageState('pt'); // Default fallback
      }
    }
  }, []);

  const setLanguage = (lang: Language) => {
    localStorage.setItem('pulso:lang', lang);
    setLanguageState(lang);
  };

  const t = useCallback((key: string, variables?: Record<string, string>): string => {
    let text = translations[language][key] || translations['pt'][key] || key;
    
    if (variables) {
      Object.keys(variables).forEach((varKey) => {
        text = text.replace(`{${varKey}}`, variables[varKey]);
      });
    }
    
    return text;
  }, [language]);

  useEffect(() => {
    console.log(`[LanguageContext] Language changed to: ${language}`);
    document.documentElement.lang = language === 'pt' ? 'pt-BR' : language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextProps => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
